name: Docker Build and Image Scanning

on:
  pull_request_target:
    types: [labeled, synchronize]

permissions: write-all

jobs:
  label:
    name: Check Labels
    runs-on: ubuntu-latest
    steps:
      #- name: Has semver label
      #  uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    valid-labels: 'major, minor, patch'
      #    pull-request-number: ${{ github.event.pull_request.number }}
      #    disable-reviews: true

      - name: Has change type label
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-labels: 'feature, enhancement, fix, bugfix, bug, chore'
          pull-request-number: ${{ github.event.pull_request.number }}
          disable-reviews: true
  
  trivy-analysis:
    runs-on: ubuntu-latest
    needs: label

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build an image from Dockerfile
      run: |
        docker build -t docker.io/jingood2/petclinic-demo:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/jingood2/petclinic-demo:${{ github.sha }}'
        #exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    #- name: Setup Trivy
    #  uses: actions/setup-docker@v1
    #  with:
    #    tags: latest

    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v2
    #-
    #  name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v2
#
#    - name: Run Trivy SBOM analysis
#      uses: docker://aquasec/trivy:latest
#      with:
#        args: sbom --format cycyclonedx 
#
#    - name: Upload SBOM to artifact storage
#      uses: actions/upload-artifact@v1
#      with:
#        name: trivy-sbom
#        path: sbom.xml