name: "CI Pipeline"

on:
  #push:
  #  branches: [ main ]
  pull_request:

permissions: write-all

jobs:
  ci:
    uses: ./.github/workflows/build-and-scanning.yml
    with:
      docker-image: 'docker.io/jingood2/petclinic-demo'
    secrets: inherit

  dev-app1-cd:
    needs: [ci]
    uses: ./.github/workflows/update-manifest.yml
    with:
      DOCKER_IMAGE_REPO: 'jingood2/petclinic-demo' 
      GITOPS_REPO: 'jingood2/petclinic-multi-env-apps-gitops'
      K8S_YAML_DIR: './apps/petclinic-demo'
      BRANCH: 'chore/multi-env-deployment'
      ENVIRONMENT: 'dev/app1'
    secrets: inherit
  
  dev-app2-cd:
    needs: [ci]
    uses: ./.github/workflows/update-manifest.yml
    with:
      DOCKER_IMAGE_REPO: 'jingood2/petclinic-demo' 
      GITOPS_REPO: 'jingood2/petclinic-multi-env-apps-gitops'
      K8S_YAML_DIR: './apps/petclinic-demo'
      BRANCH: 'chore/multi-env-deployment'
      ENVIRONMENT: 'dev/app2'
    secrets: inherit
  
  dev-app3-cd:
    needs: [ci]
    uses: ./.github/workflows/update-manifest.yml
    with:
      DOCKER_IMAGE_REPO: 'jingood2/petclinic-demo' 
      GITOPS_REPO: 'jingood2/petclinic-multi-env-apps-gitops'
      K8S_YAML_DIR: './apps/petclinic-demo'
      BRANCH: 'chore/multi-env-deployment'
      ENVIRONMENT: 'dev/app3'
    secrets: inherit
  
  #approval:

  #prod-cd:
  #  needs: [dev-cd,approval]
  #  permissions:
  #    id-token: write  # need this for OIDC
  #    contents: read   # This is required for actions/checkout
  #  uses: ./.github/workflows/update-manifest.yml
  #  with:
  #    DOCKER_IMAGE_REPO: 'docker.io/jingood2/petclinic-demo' 
  #    GITOPS_REPO: 'jingood2/petclinic-demo-gitops'
  #    K8S_YAML_DIR: './apps/petclinic-demo'
  #    BRANCH: 'main'
  #    ENVIRONMENT: 'prod'
  #  secrets: inherit
